[package]
name = "blobdb-cli"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blobdb = { path = "../lib" }
clap = { version = "=4.5.54", features = ["derive"] }
